### PR TITLE
survey info

### PR DESCRIPTION
**Pull request by lspitler**

### CODE REVIEW

**Comment by manodeep** [comment]
@lspitler are people okay with having this info public?

**Comment by lspitler** [comment]
@manodeep just verified with the PIs it is OK to release it.

**Comment by manodeep** [comment]
@lspitler Thanks for checking! 

One last thing - if you rename the file as `.md`, and then follow [this](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables), the table will get nicely formatted.

**Comment by lspitler** [comment]
OK @manodeep I created an issue for this to deal table formatting with later. Will merge now & close.

**Comment by manodeep** [comment]
Great!

**Pull request merged**
